version: "2"
run:
  timeout: 5m
linters:
  default: none
  enable:
    - contextcheck
    - copyloopvar
    - errcheck
    - errname
    - errorlint
    - goconst
    - gocritic
    - gosec
    - govet
    - importas
    - ineffassign
    - makezero
    - nlreturn
    - noctx
    - prealloc
    - revive
    - staticcheck
    - unused
  settings:
    nlreturn:
      block-size: 7
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - goconst
        path: (.+)_test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
