before:
  hooks:
    - make dep
builds:
  - env:
      - CGO_ENABLED=0
    main: ./cmd/arangom/main.go
    goos:
      - linux
      - windows
      - darwin
dist: bin
archives:
  - name_template: >-
      {{- .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end -}}
checksum:
  name_template: 'checksums.txt'
signs:
  - artifacts: all
snapshot:
  name_template: "{{ incpatch .Version }}-next"
milestones:
  - close: true
    fail_on_error: true
changelog:
  disable: true
brews:
  -
    repository:
      owner: gabor-boros
      name: homebrew-brew
    commit_author:
      name: "Gabor Boros"
      email: gabor.brs@gmail.com
    directory: Formula
    homepage: "https://github.com/gabor-boros/arangom"
    description: "Run ArangoDB migrations with ease."
    license: "MIT"
    dependencies:
      - name: go
        type: build
    custom_block: |
      head "https://github.com/gabor-boros/arangom", branch: "main"

      livecheck do
        url "https://github.com/gabor-boros/arangom/releases"
        regex(/^v(\d+(?:\.\d+)+)$/i)
      end
