version: 2
before:
  hooks:
    - make dep
builds:
  - env:
      - CGO_ENABLED=0
    main: ./cmd/arangom/main.go
    goos:
      - linux
      - windows
      - darwin
dist: bin
archives:
  - name_template: >-
      {{- .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end -}}
checksum:
  name_template: 'checksums.txt'
signs:
  - artifacts: all
snapshot:
  version_template: "{{ incpatch .Version }}-next"
milestones:
  - close: true
    fail_on_error: true
changelog:
  disable: true
homebrew_casks:
  - repository:
      owner: gabor-boros
      name: homebrew-brew
    commit_author:
      name: "Gabor Boros"
      email: gabor.brs@gmail.com
    homepage: "https://github.com/gabor-boros/arangom"
    description: "Run ArangoDB migrations with ease."
    license: "MIT"
    url:
      verified: "github.com/gabor-boros/arangom/"
    hooks:
      post:
        install: |
          if OS.mac?
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/arangom"]
          end
    custom_block: |
      head "https://github.com/gabor-boros/arangom", branch: "main"

      livecheck do
        url "https://github.com/gabor-boros/arangom/releases"
        regex(/^v(\d+(?:\.\d+)+)$/i)
      end
