name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
          cache: true
      - name: Go CI Lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.12.2

  test:
    strategy:
      fail-fast: false
      matrix:
        go:
          - '1.24'
          - '1.25'
          - '1.26'
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go }}
          cache: true
      - name: Test
        run: make test
      - name: Build
        run: go build -o ./bin/arangom ./cmd/arangom
      - name: Stash test results
        uses: actions/upload-artifact@v7
        with:
          name: ${{ matrix.os }}-${{ matrix.go }}
          path: .coverage.out
          retention-days: 7
          include-hidden-files: true
          if-no-files-found: error

  coverage:
    name: coverage
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      - uses: actions/checkout@v7
      - name: Unstash test results
        uses: actions/download-artifact@v8
        with:
          name: ubuntu-latest-1.26
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./.coverage.out
          flags: unittests
          name: ubuntu-latest-1.26
          fail_ci_if_error: true
