name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: "ubuntu-latest"
    env:
      GO111MODULE: on
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '^1.22'
      - name: Go CI Lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          args: --timeout 5m
  test:
    strategy:
      matrix:
        go:
          - '1.21'
          - '1.22'
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: '${{ matrix.os }}'
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '${{ matrix.go }}'
      - name: Test
        run: make test
      - name: Build
        run: go build -o ./bin/arangom ./cmd/arangom
      - name: Stash test results
        uses: actions/upload-artifact@master
        with:
          name: "${{ matrix.os }}-${{ matrix.go }}"
          path: .coverage.out
          retention-days: 7
  coverage:
    name: coverage
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      - uses: actions/checkout@v4
      - name: Unstash test results
        uses: actions/download-artifact@master
        with:
          name: ubuntu-latest-1.22
      - name: Upload test results
        uses: paambaati/codeclimate-action@v6
        env:
          CC_TEST_REPORTER_ID: c9d94a2c1e909f32ec045ed9653456f64c0666bfde95012e9b913dbe4b988020
        with:
          prefix: github.com/${{github.repository}}
          coverageLocations: ${{github.workspace}}/.coverage.out:gocov
